application: heniac1000
version: 1
runtime: python
api_version: 1

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css


- url: /
  script: main.py
  login: required
  secure: always

- url: /admin
  script: main.py
  login: admin
  secure: always


- url: /api/.*
  script: api.py
  login: required
  secure: always

- url: /_api/.*
  script: api.py
  login: admin
  secure: always

builtins:
- datastore_admin: on
- remote_api: on

inbound_services:
- channel_presence

